/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as jobManager from "./JobManager";
export type { jobManager };
export type { JobManager } from "./JobManager";
