/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ExtractorInterface extends Interface {
  getFunction(
    nameOrSignature: "extractResult" | "priceFor" | "readResult",
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "extractResult",
    values: [BytesLike],
  ): string;
  encodeFunctionData(functionFragment: "priceFor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "readResult",
    values: [BytesLike],
  ): string;

  decodeFunctionResult(
    functionFragment: "extractResult",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "priceFor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "readResult", data: BytesLike): Result;
}

export interface Extractor extends BaseContract {
  connect(runner?: ContractRunner | null): Extractor;
  waitForDeployment(): Promise<this>;

  interface: ExtractorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  extractResult: TypedContractMethod<[data: BytesLike], [string], "view">;

  priceFor: TypedContractMethod<[], [string], "view">;

  readResult: TypedContractMethod<[data: BytesLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: "extractResult",
  ): TypedContractMethod<[data: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "priceFor",
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "readResult",
  ): TypedContractMethod<[data: BytesLike], [bigint], "view">;

  filters: {};
}
