/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAttestationVerifier } from "./IAttestationVerifier";
export type { IExtractor } from "./IExtractor";
export type { IValidator } from "./IValidator";
