/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IExtractor,
  IExtractorInterface,
} from "../../../../contracts/JobManager/Interfaces.sol/IExtractor";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "extractResult",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IExtractor__factory {
  static readonly abi = _abi;
  static createInterface(): IExtractorInterface {
    return new Interface(_abi) as IExtractorInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IExtractor {
    return new Contract(address, _abi, runner) as unknown as IExtractor;
  }
}
