/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IValidator,
  IValidatorInterface,
} from "../../../../contracts/JobManager/Interfaces.sol/IValidator";

const _abi = [
  {
    inputs: [],
    name: "totalEscrow",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "actor",
        type: "address",
      },
    ],
    name: "validate",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IValidator__factory {
  static readonly abi = _abi;
  static createInterface(): IValidatorInterface {
    return new Interface(_abi) as IValidatorInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IValidator {
    return new Contract(address, _abi, runner) as unknown as IValidator;
  }
}
