/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfacesSol from "./Interfaces.sol";
export type { interfacesSol };
import type * as mockSol from "./Mock.sol";
export type { mockSol };
export type { Token } from "./Token";
